//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IClothingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPassword
    {
        public Nullable<int> customerID { get; set; }
        public Nullable<int> adminID { get; set; }
        public string userAccountName { get; set; }
        public string userEncryptedPassword { get; set; }
        public int passwordExpiryTime { get; set; }
        public System.DateTime userAccountExpiryDate { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
